routes/web.php
<?php
/*
** Author : Sands, muhammad.arisandi@mncgroup.com
** Date   : November 2020
*/

Route::get('/sands/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

// Dashboard
Route::get('/', function(){
    return redirect('/home');
});

//Auth
Route::group(['as' => 'auth.'], function () {
    Route::get('login', 'AuthenticateController@login')->name('login');
    Route::post('login', 'AuthenticateController@loginProc')->name('login.proc');
});


Route::group(['middleware' => ['auth']], function() {
    Route::get('logout', 'AuthenticateController@logout')->name('logout');

    //Home
    Route::get('/home', 'HomeController@index')->name('home.index');

    //ACL
    Route::group(['prefix' => 'acl', 'as' => 'acl.'], function () {
        /***** ROLE ******/
        Route::middleware('permission:show-role')->get('role', 'AdminAcl\AclRoleController@role')->name('role');
        Route::middleware('permission:show-role')->get('role/{role}', 'AdminAcl\AclRoleController@roleShow')->name('role.show');
        Route::middleware('permission:create-role')->post('role', 'AdminAcl\AclRoleController@roleStore')->name('role.store');
        Route::middleware('permission:update-role')->post('role/{role}', 'AdminAcl\AclRoleController@roleUpdate')->name('role.update');
        Route::middleware('permission:delete-role')->delete('role/{role}', 'AdminAcl\AclRoleController@roleDelete')->name('role.delete');

        /***** USER ******/
        Route::middleware('permission:show-user')->get('user', 'AdminAcl\UserController@index')->name('user');
        Route::middleware('permission:show-user')->get('user/{user}', 'AdminAcl\UserController@userShow')->name('user.show');
        Route::middleware('permission:create-user')->post('user', 'AdminAcl\UserController@userStore')->name('user.store');
        Route::middleware('permission:update-user')->post('user/{user}', 'AdminAcl\UserController@userUpdate')->name('user.update');
        Route::middleware('permission:delete-user')->delete('user/{user}', 'AdminAcl\UserController@userDelete')->name('user.delete');

        /***** AUTHORIZATION ******/
        Route::get('/authorization','AdminAcl\AuthorizationController@index')->name('authorization');

        /***** MODULE ******/
        Route::get('/module','AdminAcl\ModuleController@index')->name('module');
        Route::get('/module/gettabledata/{role_id}','AdminAcl\ModuleController@getTableData')->name('module.gettabledata'); //show per role
        Route::get('/module/{module}','AdminAcl\ModuleController@show')->name('module.show');
        Route::post('/module','AdminAcl\ModuleController@moduleStore')->name('module.store');
        Route::post('/module/{module}','AdminAcl\ModuleController@moduleUpdate')->name('module.update');


        /***** MENU ******/
        Route::get('/menu','AdminAcl\MenuController@index')->name('menu');
        Route::post('/menu','AdminAcl\MenuController@menuStore')->name('menu.store');

        /***** PERMISSION ******/
        Route::get('/permission','AdminAcl\PermissionController@index')->name('permission');
        Route::get('/permission/{id}','AdminAcl\PermissionController@show')->name('permission.show');
        Route::post('/permission/attachpermission','AdminAcl\PermissionController@attachPermission')->name('permission.attachperm');
        Route::post('/permission/detachpermission','AdminAcl\PermissionController@detachPermission')->name('permission.detachperm');
    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    //Status Users Const
    const STATUS_ACTIVE = '1';
    const STATUS_NONACTIVE = '2';

    const DEFAULT_PASS = '123456789';

    //Status Users Array
    public static $statusses = [
        1 => "Active",
        2 => "Non Active",
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AdminAcl/UserController.php
<?php
/*
** Author : Sands, muhammad.arisandi@mncgroup.com
** Date   : November 2020
*/
namespace App\Http\Controllers\AdminAcl;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\HttpFoundation\Response;
use App\Models\Role;
use App\Models\User;
use Auth;
use App\Http\Library\Serializer;


class UserController extends Controller
{
    private function getValidator($method, Request $request,$id=null)
    {
        if($method == 'userStore'){
            return Validator::make($request->all(),[
                'fullname' => 'required|string|max:255',
                'username' => 'required|string|max:255',
                'email' => 'required|string|email|max:255|unique:users',
                'role_id' => 'required|integer|exists:roles,id',
                'status' => 'required'
            ]);
        }else if ($method =='userUpdate'){
            return Validator::make($request->all(),[
                'fullname' => 'required|string|max:255',
                'username' => 'required|string|max:255',
                'email' => 'required|string|email|max:255|unique:users,email,'.$id,
                'role_id' => 'required|integer|exists:roles,id',
                'status' => 'required'
            ]);
        }

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        $statusses = User::$statusses;
        $users = User::with('roles')->get();
        return view('acl.user.index', compact('users', 'roles', 'statusses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function userStore(Request $request)
    {
        $validator = $this->getValidator('userStore',$request);

        if($validator->fails()){
            $messages = implode(',', array_column($validator->messages()->toArray(), 0));
            return redirect()->back()->with('msg', $messages);
        }else{
            DB::beginTransaction();
            try {
                $messages =  "Gagal Simpan Data";
                $user = new User;
                $user->fullname = $request->fullname;
                $user->email = $request->email;
                $user->username = $request->username;
                $user->password = bcrypt(User::DEFAULT_PASS);
                if($user->save()){
                    $user->attachRole(Role::find($request->role_id));
                    $messages = "Berhasil Simpan Data";
                    DB::commit();
                }
            } catch (\Exception $e) {
                DB::rollback();
                $messages = $e;
                //throw $e;
            } catch (\Throwable $e) {
                DB::rollback();
                $messages = $e;
                //throw $e;
            }

            return redirect()->back()->with('msg', $messages);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function userShow(User $user)
    {
        $roles = Role::all();
        $statusses = User::$statusses;
        return view('acl.user._show', compact('user', 'roles', 'statusses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function userUpdate(Request $request, User $user)
    {
        $id = !empty($user->id) ? $user->id : null;
        $validator = $this->getValidator('userUpdate',$request, $id);
        $messages = "";

        if($validator->fails()){
            $messages = implode(',',array_column($validator->messages()->toArray(),0));
        }else{
            DB::beginTransaction();
            try {
                if($user === null){
                    $messages = "User does not exist";
                }else{
                    if($request->fullname != null && $request->fullname != '')
                        $user->fullname = $request->fullname;
                    if($request->username != null && $request->username != '')
                        $user->username = $request->username;
                    if($request->email != null && $request->email != '')
                        $user->email = $request->email;
                    if($request->status != null && $request->status != '')
                        $user->status = $request->status;

                    if($user->save()){
                        $user->detachRoles($user->roles);
                        $user->attachRole(Role::find($request->role_id));
                        $messages = "Berhasil Simpan Data";
                        DB::commit();
                    }
                }
            } catch (\Exception $e) {
                DB::rollback();
                $messages = $e;
                //throw $e;
            } catch (\Throwable $e) {
                DB::rollback();
                $messages = $e;
                //throw $e;
            }
        }

        return redirect()->back()->with('msg', $messages);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function userDelete(User $user)
    {
        $statusCode = Response::HTTP_BAD_REQUEST;
        $message = '';
        $status = false;

        if($user === null){
            $message = "User does not exist";
            $resource = Serializer::serializeItem($status, $message);
            return response()->json($resource,$statusCode);
        }

        DB::beginTransaction();
        try {
            $message = "Delete Data Tidak Berhasil, Data tidak ditemukan";
            if($user->delete()){
                DB::commit();
                $message = "Delete Data Berhasil";
                $statusCode = Response::HTTP_OK;
                $status = true;
            }
        } catch (\Exception $e) {
            DB::rollback();
            $message = $e;
            //throw $e;
        } catch (\Throwable $e) {
            DB::rollback();
            $message = $e;
            //throw $e;
        }
        $resource = Serializer::serializeItem($status, $message);
        return response()->json($resource, $statusCode);
    }



}

resources/views/acl/user/_show.blade.php
<div class="modal-header">
    <h5 class="modal-title">Update User</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i aria-hidden="true" class="ki ki-close"></i>
    </button>
</div>
<div class="modal-body">
    <form action="{{route('acl.user.update', ['user' => $user->id])}}" method="POST" id="formUpdate">
        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label>Fullname</label>
            <input type="text" class="form-control" name="fullname" required placeholder="Enter Value" value="{{$user->fullname}}">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" required placeholder="Enter Value" value="{{$user->email}}">
        </div>
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" name="username" required placeholder="Enter Value" value="{{$user->username}}">
        </div>
        <div class="form-group">
            <label>Role</label>
            <select name="role_id" class="form-control">
                <option value="" selected disabled>== Pilih ==</option>
                @foreach($roles as $key => $role)
                    @php
                        $selected = ($role->id == $user->roles[0]->id) ? " SELECTED " : "";
                    @endphp
                    <option {{$selected}} value="{{$role->id}}"> {{$role->name}} </option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label>Status</label>
            <select name="status" class="form-control">
                @foreach($statusses as $key => $status)
                    @php
                    $selected = ($key == $user->status) ? " SELECTED " : "";
                    @endphp
                    <option {{$selected}} value="{{$key}}"> {{$status}} </option>
                @endforeach
            </select>
        </div>

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary updateBtn">Update</button>
    </form>
</div>

resources/views/acl/user/index.blade.php
@extends('layouts.master')

@section('title') Users @endsection

@section('content')
    <!--begin::Content-->
    <div class="content  d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
            <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">
                            Users
                        </h5>
                        <!--end::Page Title-->
                        <!--begin::Breadcrumb-->
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">
                                    ACL
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">
                                    Users
                                </a>
                            </li>
                        </ul>
                        <!--end::Breadcrumb-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
                <!--begin::Toolbar-->
                <div class="d-flex align-items-center">
                    <!--begin::Actions-->
                    <a href=" {{ url()->previous() }} " class="btn btn-light-primary font-weight-bolder btn-sm">
                        Back
                    </a>
                    <!--end::Actions-->
                </div>
                <!--end::Toolbar-->
            </div>
        </div>
        <!--end::Subheader-->

        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class=" container ">
                @if (\Session::has('msg'))
                    <div class="alert alert-custom alert-notice alert-light-primary fade show" role="alert">
                        <div class="alert-icon"><i class="flaticon-warning"></i></div>
                        <div class="alert-text">{!! \Session::get('msg') !!}</div>
                        <div class="alert-close">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true"><i class="ki ki-close"></i></span>
                            </button>
                        </div>
                    </div>
                @endif
                <!--begin::Card-->
                <div class="card card-custom gutter-b">
                    <div class="card-header flex-wrap py-3">
                        <div class="card-title">
                            <h3 class="card-label">
                                List Users
                                <span class="d-block text-muted pt-2 font-size-sm">ACL</span>
                            </h3>
                        </div>
                        <div class="card-toolbar">
                            <!--begin::Button-->
                            <a href="#" id="newDataBtn" class="btn btn-primary font-weight-bolder">
                                    <span class="svg-icon svg-icon-md">
                                       <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                                       <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                             <rect x="0" y="0" width="24" height="24"/>
                                             <circle fill="#000000" cx="9" cy="15" r="6"/>
                                             <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"/>
                                          </g>
                                       </svg>
                                        <!--end::Svg Icon-->
                                    </span>
                                New User
                            </a>
                            <!--end::Button-->
                        </div>
                    </div>
                    <div class="card-body">
                        <!--begin: Datatable-->
                        <table class="table table-bordered table-checkable" id="tableUser">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Fullname</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Role</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                                @php $no = 1; @endphp
                                @foreach($users as $user)
                                    @php
                                    $status = $user->status == 1 ? "Active" : "Non Active";
                                    @endphp
                                    <tr>
                                        <td>{{$no}}</td>
                                        <td>{{$user->fullname}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->username}}</td>
                                        <td>{{$user->roles[0]->name}}</td>
                                        <td>{{$status}}</td>
                                        <td>
                                            <button class="btn btn-transparent-primary font-weight-bold mr-2 editBtn" id="editBtn{{$user->id}}" data-id="{{$user->id}}">Edit </button>
                                            <button class="btn btn-transparent-danger font-weight-bold mr-2 deleteBtn" id="deleteBtn{{$user->id}}" data-id="{{$user->id}}">Delete</button>
                                        </td>
                                    </tr>
                                    @php $no++; @endphp
                                @endforeach
                            </tbody>
                        </table>
                        <!--end: Datatable-->
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>

    {{--    add modal--}}
    <div class="modal fade" tabindex="-1" role="dialog" id="modalUser">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i aria-hidden="true" class="ki ki-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('acl.user.store')}}" method="POST" id="formCreate">
                        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

                        <div class="form-group">
                            <label>Fullname</label>
                            <input type="text" class="form-control" name="fullname" required placeholder="Enter Value">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" class="form-control" name="email" required placeholder="Enter Value">
                        </div>
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username" required placeholder="Enter Value">
                        </div>
                        <div class="form-group">
                            <label>Role</label>
                            <select name="role_id" class="form-control">
                                <option value="" selected disabled>== Pilih ==</option>
                                @foreach($roles as $key => $role)
                                    <option value="{{$role->id}}"> {{$role->name}} </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <select name="status" class="form-control">
                                @foreach($statusses as $key => $status)
                                    <option value="{{$key}}"> {{$status}} </option>
                                @endforeach
                            </select>
                        </div>



                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {{--    edit modal--}}
    <div class="modal fade" tabindex="-1" role="dialog" id="modalUserEdit">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modalUserEditContent"></div>
            </div>
        </div>
    </div>

    <!--end::Content-->
@endsection

@section('script')
    <script src="/js/acl/user/index.js?v=sands{{time()}}"></script>
@endsection