routes/web.php
<?php
/*
** Author : Sands, muhammad.arisandi@mncgroup.com
** Date   : November 2020
*/

Route::get('/sands/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

// Dashboard
Route::get('/', function(){
    return redirect('/home');
});

//Auth
Route::group(['as' => 'auth.'], function () {
    Route::get('login', 'AuthenticateController@login')->name('login');
    Route::post('login', 'AuthenticateController@loginProc')->name('login.proc');
});


Route::group(['middleware' => ['auth']], function() {
    Route::get('logout', 'AuthenticateController@logout')->name('logout');

    //Home
    Route::get('/home', 'HomeController@index')->name('home.index');

    //ACL
    Route::group(['prefix' => 'acl', 'as' => 'acl.'], function () {
        /***** ROLE ******/
        Route::middleware('permission:show-role')->get('role', 'AdminAcl\AclRoleController@role')->name('role');
        Route::middleware('permission:show-role')->get('role/{role}', 'AdminAcl\AclRoleController@roleShow')->name('role.show');
        Route::middleware('permission:create-role')->post('role', 'AdminAcl\AclRoleController@roleStore')->name('role.store');
        Route::middleware('permission:update-role')->post('role/{role}', 'AdminAcl\AclRoleController@roleUpdate')->name('role.update');
        Route::middleware('permission:delete-role')->delete('role/{role}', 'AdminAcl\AclRoleController@roleDelete')->name('role.delete');

        /***** USER ******/
        Route::middleware('permission:show-user')->get('user', 'AdminAcl\UserController@index')->name('user');
        Route::middleware('permission:show-user')->get('user/{user}', 'AdminAcl\UserController@userShow')->name('user.show');
        Route::middleware('permission:create-user')->post('user', 'AdminAcl\UserController@userStore')->name('user.store');
        Route::middleware('permission:update-user')->post('user/{user}', 'AdminAcl\UserController@userUpdate')->name('user.update');
        Route::middleware('permission:delete-user')->delete('user/{user}', 'AdminAcl\UserController@userDelete')->name('user.delete');

        /***** AUTHORIZATION ******/
        Route::get('/authorization','AdminAcl\AuthorizationController@index')->name('authorization');

        /***** MODULE ******/
        Route::get('/module','AdminAcl\ModuleController@index')->name('module');
        Route::get('/module/gettabledata/{role_id}','AdminAcl\ModuleController@getTableData')->name('module.gettabledata'); //show per role
        Route::get('/module/{module}','AdminAcl\ModuleController@show')->name('module.show');
        Route::post('/module','AdminAcl\ModuleController@moduleStore')->name('module.store');
        Route::post('/module/{module}','AdminAcl\ModuleController@moduleUpdate')->name('module.update');


        /***** MENU ******/
        Route::get('/menu','AdminAcl\MenuController@index')->name('menu');
        Route::post('/menu','AdminAcl\MenuController@menuStore')->name('menu.store');

        /***** PERMISSION ******/
        Route::get('/permission','AdminAcl\PermissionController@index')->name('permission');
        Route::get('/permission/{id}','AdminAcl\PermissionController@show')->name('permission.show');
        Route::post('/permission/attachpermission','AdminAcl\PermissionController@attachPermission')->name('permission.attachperm');
        Route::post('/permission/detachpermission','AdminAcl\PermissionController@detachPermission')->name('permission.detachperm');
    });

});

app/Models/Module.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
    public function permissions(){
        return $this->hasMany('App\Models\Permission','module_id');
    }
}

app/Http/Controllers/AdminAcl/ModuleController.php
<?php

namespace App\Http\Controllers\AdminAcl;

use App\Models\Permission;
use App\Models\PermissionRole;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Module;
use App\Models\Role;
use Validator;
use App\Http\Library\Serializer;
use Illuminate\Support\Facades\DB;

class ModuleController extends Controller
{
    private function getValidator($method, Request $request,$id=null)
    {
        if($method == 'moduleStore'){
            return \Illuminate\Support\Facades\Validator::make($request->all(),[
                'name' => 'required',
                'display_name' => 'required'
            ]);
        }elseif($method == 'moduleUpdate'){
            return \Illuminate\Support\Facades\Validator::make($request->all(),[
                'name' => 'required',
                'display_name' => 'required',
                'status' => 'required'
            ]);
        }

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $modules = Module::with('permissions')->get();
        return view('acl.module.index', compact('modules'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Module $module)
    {
        if(!$module){
            $message = "Module Not Found";
            $statusCode = Response::HTTP_BAD_REQUEST;
            $resource = Serializer::serializeCollection(false,$message);
            return response()->json($resource,$statusCode);
        }

        return view('acl.module._show', compact('module'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function getTableData(Request $request,$role_id)
    {
        //check
        if(Role::find($role_id) === null){
            $message = "Role with id: ".$role_id.", does not exist";
            $statusCode = 500;
            $resource = Serializer::serializeItem(false,$message);
            return response()->json($resource,$statusCode);
        }
        if($request->has('module_id')){
            $module_id = $request->module_id;
            if(Module::find($module_id) === null){
                $message = "Module with id: ".$module_id.", does not exist";
                $statusCode = 500;
                $resource = Serializer::serializeItem(false,$message);
                return response()->json($resource,$statusCode);
            }
        }else{
            $module_id = null;
        }


        $query = "SELECT z.id,z.name, IF(a.name IS NULL,0,1) as show_bool, a.id as \"show\", IF(b.name IS NULL,0,1) as create_bool ,
        b.id as \"create\",IF(c.name IS NULL,0,1) as update_bool, c.id as \"update\",IF(d.name IS NULL,0,1) delete_bool, d.id as \"delete\" 
        from modules z
        left join
        (select a.id,a.display_name, IF(b.permission_id IS NULL,null,a.name) as name,a.module_id from (select id, name, module_id, display_name from permissions where name like 'show%' ) a
        left join permission_role b on a.id = b.permission_id and role_id = ".$role_id.") a on z.id = a.module_id
        left join
        (select a.id,a.display_name, IF(b.permission_id IS NULL,null,a.name) as name,a.module_id from (select id, name, module_id, display_name from permissions where name like 'create%' ) a
        left join permission_role b on a.id = b.permission_id and role_id = ".$role_id.") b on z.id = b.module_id
        left join
        (select a.id,a.display_name, IF(b.permission_id IS NULL,null,a.name) as name,a.module_id from (select id, name, module_id, display_name from permissions where name like 'update%' ) a
        left join permission_role b on a.id = b.permission_id and role_id = ".$role_id.") c on z.id = c.module_id
        left join
        (select a.id,a.display_name, IF(b.permission_id IS NULL,null,a.name) as name,a.module_id from (select id, name, module_id, display_name from permissions where name like 'delete%' ) a
        left join permission_role b on a.id = b.permission_id and role_id = ".$role_id.") d on z.id = d.module_id";


        if($module_id != null) $query .= "where z.id = ".$module_id;

        $query .= " order by z.id asc";
        $data = DB::select(DB::raw($query));

        //Remap Data For Show In Datatable
        $data = collect($data)->map(function($v, $k){
            $v->no = ++$k;
            $checked_show = ($v->show_bool == 1) ? " CHECKED " : "";
            $checked_update = ($v->update_bool == 1) ? " CHECKED " : "";
            $checked_create = ($v->create_bool == 1) ? " CHECKED " : "";
            $checked_delete = ($v->delete_bool == 1) ? " CHECKED " : "";

            $disabled_show = empty($v->show) ? " DISABLED " : "";
            $disabled_update = empty($v->update) ? " DISABLED " : "";
            $disabled_create = empty($v->create) ? " DISABLED " : "";
            $disabled_delete = empty($v->delete) ? " DISABLED " : "";

            $disabled_show_class_label = empty($v->show) ? " checkbox-disabled " : "";
            $disabled_update_class_label = empty($v->update) ? " checkbox-disabled " : "";
            $disabled_create_class_label = empty($v->create) ? " checkbox-disabled " : "";
            $disabled_delete_class_label = empty($v->delete) ? " checkbox-disabled " : "";

            $el_checkbox_show = "<label class=\"checkbox checkbox-lg $disabled_show_class_label\">
                                <input type=\"checkbox\" ".$checked_show." ".$disabled_show." class=\"checkboxPerm\" value=\" ".$v->show." \">
                                <span></span>
                            </label>";
            $el_checkbox_update = "<label class=\"checkbox checkbox-lg $disabled_update_class_label\">
                                <input type=\"checkbox\" ".$checked_update." ".$disabled_update." class=\"checkboxPerm\" value=\" ".$v->update." \">
                                <span></span>
                            </label>";
            $el_checkbox_create = "<label class=\"checkbox checkbox-lg $disabled_create_class_label\">
                                <input type=\"checkbox\" ".$checked_create." ".$disabled_create." class=\"checkboxPerm\" value=\" ".$v->create." \">
                                <span></span>
                            </label>";
            $el_checkbox_delete = "<label class=\"checkbox checkbox-lg $disabled_delete_class_label\">
                                <input type=\"checkbox\" ".$checked_delete." ".$disabled_delete." class=\"checkboxPerm\" value=\" ".$v->delete." \">
                                <span></span>
                            </label>";

            $v->checked_show = $el_checkbox_show;
            $v->checked_update = $el_checkbox_update;
            $v->checked_create = $el_checkbox_create;
            $v->checked_delete = $el_checkbox_delete;

            return $v;
        });


        $records_total = count($data);
        $result['data'] = $data;
        $result['recordsTotal'] = $records_total;
        $result['recordsFiltered'] = $records_total;
        $statusCode = Response::HTTP_OK;

        return response()->json($result, $statusCode);

    }

    public function moduleStore(Request $request)
    {
        $validator = $this->getValidator('moduleStore',$request);

        if($validator->fails()){
            $messages = implode(',', array_column($validator->messages()->toArray(), 0));
            return redirect()->back()->with('msg', $messages);
        }else{
            DB::beginTransaction();
            try {
                $permissions = $request->permissions;
                if(count($permissions) > 0){
                    $module = new Module();
                    $module->name = strtolower(str_replace(' ', '',  $request->name));
                    $module->display_name = $request->display_name;
                    $module->description = !empty($request->description) ?  $request->description : '';
                    $module->save();

                    foreach($permissions as $k => $permission){
                        $permission_name = $k.'-'.$module->name;
                        $display_name = ucwords($k.' '.$module->name);

                        $module_id = $module->id;
                        DB::table('permissions')->insert([
                            'name' => $permission_name,
                            'display_name' => $display_name,
                            'description' => $display_name,
                            'module_id' => $module_id,
                        ]);
                    }

                    $messages = "Data Berhasil Disimpan";
                }else{
                    $messages = "Data Gagal Disimpan, Permission Belum Dipilih";
                }

                DB::commit();
            } catch (\Exception $e) {
                DB::rollback();
                $messages = $e;
                //throw $e;
            } catch (\Throwable $e) {
                DB::rollback();
                $messages = $e;
                //throw $e;
            }

            return redirect()->back()->with('msg', $messages);
        }
    }

    public function moduleUpdate(Module $module, Request $request)
    {
        $validator = $this->getValidator('moduleUpdate',$request);

        if($validator->fails()){
            $messages = implode(',', array_column($validator->messages()->toArray(), 0));
            return redirect()->back()->with('msg', $messages);
        }else{
            DB::beginTransaction();
            try {
                $permissions = $request->permissions;
                if(count($permissions) > 0){
                    $module->name = strtolower(str_replace(' ', '',  $request->name));

resources/views/acl/module/_show.blade.php
    <div class="modal-body">
        <form action="{{route('acl.module.update', ['module' => $module->id])}}" method="POST" id="formUpdate">
            <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

            <div class="form-group">
                <label>Name</label>
                <input type="text" class="form-control moduleNameInput" name="name" value="{{$module->name}}" required placeholder="ex : data-master">
            </div>
            <div class="form-group">
                <label>Display Name</label>
                <input type="text" class="form-control" name="display_name" value="{{$module->display_name}}" required placeholder="ex: Data Master">
            </div>
            <div class="form-group">
                <label>Description</label>
                <input type="text" class="form-control" name="description"  value="{{$module->description}}" placeholder="Enter Description">
            </div>

            <div class="form-group">
                <label>Status</label>
                <select name="status" id="" class="form-control">
                    @php
                            $status_active_selected = ($module->status == 1) ? " SELECTED " : "";
                            $status_nonactive_selected = ($module->status == 0) ? " SELECTED " : "";
                    @endphp
                    <option {{$status_active_selected}} value="1">Active</option>
                    <option {{$status_nonactive_selected}} value="0">Non Active</option>
                </select>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">Permissions</label>
                <div class="col-9 col-form-label">
                    <div class="checkbox-list">
                        @php
                        $components_perm = ['show', 'update', 'delete', 'create'];
                        @endphp
                        @foreach($components_perm as $component_perm)
                            @php
                                $permissions = $module->permissions->pluck('name');

                                $new_permissions = [];
                                foreach($permissions as $k => $permission){
                                    $implode = explode('-', $permission);
                                    $arr_key_implode = array_keys($implode);
                                    $end_key = end($arr_key_implode);

                                    $this_perm = $implode[0];
                                    $this_perm_name = "";
                                    foreach($implode as $key => $perm_name){
                                        if($key != 0){
                                            $prefix_strip = ($key == $end_key) ? "" : "-";
                                            $this_perm_name .= $implode[$key].$prefix_strip;
                                        }
                                    }

                                    $new_permissions[$k]['type'] = $this_perm;
                                    $new_permissions[$k]['permission'] = $permission;
                                    $new_permissions[$k]['permission_postfix'] = $this_perm_name;
                                }

                                $new_permissions = array_values($new_permissions);

                                $have_perm = array_search($component_perm, array_column($new_permissions, 'type'));

                               if($have_perm !== false){
                                   $these_perm = $new_permissions[$have_perm];
                                   $checked = "  CHECKED ";
                                   $label_check = $these_perm['type'].'-<div class="moduleName">'.$these_perm['permission_postfix'].'</div>';
                               }else{
                                   $get_postfix_from_firstdata = $new_permissions[0]['permission_postfix'];
                                   $checked = "";
                                   $label_check = $component_perm.'-<div class="moduleName">'.$get_postfix_from_firstdata.'</div>';
                               }

                               $html_check = '<label class="checkbox">
                                                <input type="checkbox" '.$checked.' name="permissions['.$component_perm.']">
                                                <span></span>
                                                '.$label_check.' </label>';
                            @endphp
                            {!! $html_check !!}
                        @endforeach

                    </div>
                </div>
            </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary btnUpdateSubmit">Update</button>
        </form>
    </div>

resources/views/acl/module/index.blade.php
@extends('layouts.master')

@section('title') Modules @endsection

@section('content')
    <!--begin::Content-->
    <div class="content  d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
            <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">
                            Modules
                        </h5>
                        <!--end::Page Title-->
                        <!--begin::Breadcrumb-->
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">
                                    ACL
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">
                                    Modules
                                </a>
                            </li>
                        </ul>
                        <!--end::Breadcrumb-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
                <!--begin::Toolbar-->
                <div class="d-flex align-items-center">
                    <!--begin::Actions-->
                    <a href=" {{ url()->previous() }} " class="btn btn-light-primary font-weight-bolder btn-sm">
                        Back
                    </a>
                    <!--end::Actions-->
                </div>
                <!--end::Toolbar-->
            </div>
        </div>
        <!--end::Subheader-->

        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class=" container ">
                @if (\Session::has('msg'))
                    <div class="alert alert-custom alert-notice alert-light-primary fade show" role="alert">
                        <div class="alert-icon"><i class="flaticon-warning"></i></div>
                        <div class="alert-text">{!! \Session::get('msg') !!}</div>
                        <div class="alert-close">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true"><i class="ki ki-close"></i></span>
                            </button>
                        </div>
                    </div>
                @endif

                <!--begin::Card-->
                <div class="row">
                    <div class="card card-custom wave wave-animate-slow col-md-4 ml-3">
                        <div class="card-body">
                            <div class="d-flex align-items-center p-5">
                                <div class="mr-6">
                                    <span class="svg-icon svg-icon-warning svg-icon-4x">
                                        <svg>
                                            ...
                                        </svg>
                                    </span>
                                </div>
                                <div class="d-flex flex-column">
                                    <a href="#" class="text-dark text-hover-primary font-weight-bold font-size-h4 mb-3">
                                        Manage Module
                                    </a>
                                    <div class="text-dark-75">
                                        <a href="#" id="newModuleBtn" class="btn btn-lg btn-primary font-weight-bolder">
                                            <span class="svg-icon svg-icon-md">
                                               <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                                               <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                  <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                     <rect x="0" y="0" width="24" height="24"/>
                                                     <circle fill="#000000" cx="9" cy="15" r="6"/>
                                                     <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"/>
                                                  </g>
                                               </svg>
                                                <!--end::Svg Icon-->
                                            </span>
                                            New Module
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card card-custom gutter-b mt-5">
                    <div class="card-header flex-wrap py-3">
                        <div class="card-title">
                            <h3 class="card-label">
                                List Module
                                <span class="d-block text-muted pt-2 font-size-sm">ACL</span>
                            </h3>
                        </div>
                        <div class="card-toolbar">


                        </div>
                    </div>
                    <div class="card-body">
                        <!--begin: Datatable-->
                        <table class="table table-bordered table-checkable" id="tableModule">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Module</th>
                                <th>Permissions</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $no = 1;
                            @endphp
                            @foreach($modules as $module)
                                @php
                                $permissions = $module->permissions->pluck('name');
                                $permissions_str = "";
                                foreach($permissions as $permission){
                                    $permissions_str .= $permission.", ";
                                }
                                @endphp
                                <tr>
                                    <td>{{$no}}</td>
                                    <td>{{$module->name}}</td>
                                    <td>{{$permissions_str}}</td>
                                    <td>
                                        <button class="btn btn-success btn-sm btnUpdate" data-id="{{$module->id}}">Update</button>
                                    </td>
                                </tr>
                                @php
                                    $no++;
                                @endphp
                            @endforeach
                            </tbody>
                        </table>
                        <!--end: Datatable-->
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>

    {{--    add modal--}}
    <div class="modal fade" tabindex="-1" role="dialog" id="modalModule">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add Module</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i aria-hidden="true" class="ki ki-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('acl.module.store')}}" method="POST" id="formCreate">
                        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="moduleNameInput form-control" name="name" required placeholder="ex : data-master">
                        </div>
                        <div class="form-group">
                            <label>Display Name</label>
                            <input type="text" class="form-control" name="display_name" required placeholder="ex: Data Master">
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <input type="text" class="form-control" name="description"  placeholder="Enter Description">
                        </div>
                        <div class="form-group row">
                                <label class="col-3 col-form-label">Permissions</label>
                                <div class="col-9 col-form-label">
                                    <div class="checkbox-list">
                                        <label class="checkbox">
                                            <input type="checkbox" name="permissions[show]">
                                            <span></span>
                                            show-<div class="moduleName"></div>
                                        </label>
                                        <label class="checkbox">
                                            <input type="checkbox" name="permissions[create]">
                                            <span></span>
                                            create-<div class="moduleName"></div>
                                        </label>
                                        <label class="checkbox">
                                            <input type="checkbox" name="permissions[update]">
                                            <span></span>
                                            update-<div class="moduleName"></div>
                                        </label>
                                        <label class="checkbox">
                                            <input type="checkbox" name="permissions[delete]">
                                            <span></span>
                                            delete-<div class="moduleName"></div>
                                        </label>
                                    </div>
                                </div>
                            </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {{--    edit modal--}}
    <div class="modal fade" tabindex="-1" role="dialog" id="modalUpdateModule">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Update Module</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i aria-hidden="true" class="ki ki-close"></i>
                    </button>
                </div>
                <div class="modalModuleEditContent"></div>
            </div>
        </div>
    </div>
    <!--end::Content-->
@endsection

@section('script')
    <script src="/js/acl/module/index.js?v=sands{{time()}}"></script>
@endsection