routes/web.php
<?php
/*
** Author : Sands, muhammad.arisandi@mncgroup.com
** Date   : November 2020
*/

Route::get('/sands/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

// Dashboard
Route::get('/', function(){
    return redirect('/home');
});

//Auth
Route::group(['as' => 'auth.'], function () {
    Route::get('login', 'AuthenticateController@login')->name('login');
    Route::post('login', 'AuthenticateController@loginProc')->name('login.proc');
});


Route::group(['middleware' => ['auth']], function() {
    Route::get('logout', 'AuthenticateController@logout')->name('logout');

    //Home
    Route::get('/home', 'HomeController@index')->name('home.index');

    //ACL
    Route::group(['prefix' => 'acl', 'as' => 'acl.'], function () {
        /***** ROLE ******/
        Route::middleware('permission:show-role')->get('role', 'AdminAcl\AclRoleController@role')->name('role');
        Route::middleware('permission:show-role')->get('role/{role}', 'AdminAcl\AclRoleController@roleShow')->name('role.show');
        Route::middleware('permission:create-role')->post('role', 'AdminAcl\AclRoleController@roleStore')->name('role.store');
        Route::middleware('permission:update-role')->post('role/{role}', 'AdminAcl\AclRoleController@roleUpdate')->name('role.update');
        Route::middleware('permission:delete-role')->delete('role/{role}', 'AdminAcl\AclRoleController@roleDelete')->name('role.delete');

        /***** USER ******/
        Route::middleware('permission:show-user')->get('user', 'AdminAcl\UserController@index')->name('user');
        Route::middleware('permission:show-user')->get('user/{user}', 'AdminAcl\UserController@userShow')->name('user.show');
        Route::middleware('permission:create-user')->post('user', 'AdminAcl\UserController@userStore')->name('user.store');
        Route::middleware('permission:update-user')->post('user/{user}', 'AdminAcl\UserController@userUpdate')->name('user.update');
        Route::middleware('permission:delete-user')->delete('user/{user}', 'AdminAcl\UserController@userDelete')->name('user.delete');

        /***** AUTHORIZATION ******/
        Route::get('/authorization','AdminAcl\AuthorizationController@index')->name('authorization');

        /***** MODULE ******/
        Route::get('/module','AdminAcl\ModuleController@index')->name('module');
        Route::get('/module/gettabledata/{role_id}','AdminAcl\ModuleController@getTableData')->name('module.gettabledata'); //show per role
        Route::get('/module/{module}','AdminAcl\ModuleController@show')->name('module.show');
        Route::post('/module','AdminAcl\ModuleController@moduleStore')->name('module.store');
        Route::post('/module/{module}','AdminAcl\ModuleController@moduleUpdate')->name('module.update');


        /***** MENU ******/
        Route::get('/menu','AdminAcl\MenuController@index')->name('menu');
        Route::post('/menu','AdminAcl\MenuController@menuStore')->name('menu.store');

        /***** PERMISSION ******/
        Route::get('/permission','AdminAcl\PermissionController@index')->name('permission');
        Route::get('/permission/{id}','AdminAcl\PermissionController@show')->name('permission.show');
        Route::post('/permission/attachpermission','AdminAcl\PermissionController@attachPermission')->name('permission.attachperm');
        Route::post('/permission/detachpermission','AdminAcl\PermissionController@detachPermission')->name('permission.detachperm');
    });

});

app/Models/Role.php
<?php

namespace App\Models;
use Illuminate\Support\Facades\Config;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
    public function users()
    {
        return $this->belongsToMany(
            Config::get('auth.providers.users.model'),
            Config::get('entrust.role_user_table'),
            Config::get('entrust.role_foreign_key'),
            Config::get('entrust.user_foreign_key')
        );
    }

    public function perms()
    {
        return $this->belongsToMany(
            Config::get('entrust.permission')
        // Config::get('entrust.permission_role_table'),
        // Config::get('entrust.role_foreign_key'),
        // Config::get('entrust.permission_foreign_key')
        );
    }

}

resources/views/acl/role/_show.blade.php
<div class="modal-header">
    <h5 class="modal-title">Update Role</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i aria-hidden="true" class="ki ki-close"></i>
    </button>
</div>
<div class="modal-body">
    <form action="{{route('acl.role.update', ['role' => $role->id])}}" method="POST" id="formUpdate">
        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" name="name" required placeholder="Enter Value" value="{{$role->name}}">
        </div>
        <div class="form-group">
            <label>Display Name</label>
            <input type="text" class="form-control" name="display_name" required placeholder="Enter Value" value="{{$role->display_name}}">
        </div>
        <div class="form-group">
            <label>Description</label>
            <input type="text" class="form-control" name="description" required placeholder="Enter Value" value="{{$role->description}}">
        </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary updateBtn">Update</button>
    </form>
</div>

resources/views/acl/role/index.blade.php
@extends('layouts.master')

@section('title') Roles @endsection

@section('content')
    <!--begin::Content-->
    <div class="content  d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
            <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">
                            Role
                        </h5>
                        <!--end::Page Title-->
                        <!--begin::Breadcrumb-->
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">
                                    ACL
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">
                                   Role
                                </a>
                            </li>
                        </ul>
                        <!--end::Breadcrumb-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
                <!--begin::Toolbar-->
                <div class="d-flex align-items-center">
                    <!--begin::Actions-->
                    <a href=" {{ url()->previous() }} " class="btn btn-light-primary font-weight-bolder btn-sm">
                        Back
                    </a>
                    <!--end::Actions-->
                </div>
                <!--end::Toolbar-->
            </div>
        </div>
        <!--end::Subheader-->

        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class=" container ">
                @if (\Session::has('msg'))
                    <div class="alert alert-custom alert-notice alert-light-primary fade show" role="alert">
                        <div class="alert-icon"><i class="flaticon-warning"></i></div>
                        <div class="alert-text">{!! \Session::get('msg') !!}</div>
                        <div class="alert-close">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true"><i class="ki ki-close"></i></span>
                            </button>
                        </div>
                    </div>
                @endif
                <!--begin::Card-->
                <div class="card card-custom gutter-b">
                    <div class="card-header flex-wrap py-3">
                        <div class="card-title">
                            <h3 class="card-label">
                                List Role
                                <span class="d-block text-muted pt-2 font-size-sm">ACL</span>
                            </h3>
                        </div>
                        <div class="card-toolbar">
                            <!--begin::Button-->
                            <a href="#" id="newRoleBtn" class="btn btn-primary font-weight-bolder">
                                    <span class="svg-icon svg-icon-md">
                                       <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                                       <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                             <rect x="0" y="0" width="24" height="24"/>
                                             <circle fill="#000000" cx="9" cy="15" r="6"/>
                                             <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"/>
                                          </g>
                                       </svg>
                                        <!--end::Svg Icon-->
                                    </span>
                                New Role
                            </a>
                            <!--end::Button-->
                        </div>
                    </div>
                    <div class="card-body">
                        <!--begin: Datatable-->
                        <table class="table table-bordered table-checkable" id="tableRole">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Display Name</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                                @php $no = 1; @endphp
                                @foreach($roles as $role)
                                    <tr>
                                        <td>{{$no}}</td>
                                        <td>{{$role->name}}</td>
                                        <td>{{$role->display_name}}</td>
                                        <td>{{$role->description}}</td>
                                        <td>
                                            <button class="btn btn-transparent-primary font-weight-bold mr-2 editBtn" id="editBtn{{$role->id}}" data-id="{{$role->id}}">Edit </button>
                                            <button class="btn btn-transparent-danger font-weight-bold mr-2 deleteBtn" id="deleteBtn{{$role->id}}" data-id="{{$role->id}}">Delete</button>
                                        </td>
                                    </tr>
                                    @php $no++; @endphp
                                @endforeach
                            </tbody>
                        </table>
                        <!--end: Datatable-->
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>

    {{--    add modal--}}
    <div class="modal fade" tabindex="-1" role="dialog" id="modalRole">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add Role</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i aria-hidden="true" class="ki ki-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('acl.role.store')}}" method="POST" id="formCreate">
                        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" required placeholder="Enter Value">
                        </div>
                        <div class="form-group">
                            <label>Display Name</label>
                            <input type="text" class="form-control" name="display_name" required placeholder="Enter Value">
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <input type="text" class="form-control" name="description" required placeholder="Enter Value">
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {{--    edit modal--}}
    <div class="modal fade" tabindex="-1" role="dialog" id="modalRoleEdit">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modalRoleEditContent"></div>
            </div>
        </div>
    </div>

    <!--end::Content-->
@endsection

@section('script')
    <script src="/js/acl/role/index.js?v=sands{{time()}}"></script>
@endsection